language: python
python:
- pypy
- 2.6
- 2.7
- 3.2
- 3.3
env:
- PYTHON_VM=cpython
matrix:
  include:
  - python: 2.7
    env: PYTHON_VM=ironpython
  - python: pypy
    env: PYTHON_VM=pypy
  exclude:
  - python: pypy
    env: PYTHON_VM=cpython
install:
- if [[ "$PYTHON_VM" == "cpython" ]]; then
    pip install pytest mock pytest-cov pep8 coveralls;
  fi
- if [[ "$PYTHON_VM" == "pypy" ]]; then
    pip install pytest mock;
  fi
- if [[ "$PYTHON_VM" == "ironpython" ]]; then
    sudo apt-get install -qq mono-devel mercurial;
    curl -L -o /tmp/ironpython.zip https://github.com/IronLanguages/main/releases/download/ipy-2.7.4/IronPython-2.7.4.zip;
    unzip /tmp/ironpython.zip;
    hg clone https://bitbucket.org/dahlia/py-ironpython /tmp/py-lib;
    hg clone https://bitbucket.org/dahlia/pytest-ironpython /tmp/pytest;
    ln -s /tmp/py-lib/py;
    ln -s /tmp/pytest/_pytest;
    ln -s /tmp/pytest/pytest.py;
    pushd /tmp;
    curl https://pypi.python.org/packages/source/m/mock/mock-1.0.1.tar.gz | tar xvfz -;
    popd;
    ln -s /tmp/mock-1.0.1/mock.py
  fi
script:
- if [[ "$PYTHON_VM" == "cpython" ]]; then
    python -mlibearth.version;
    py.test --cov libearth --durations=20 tests || exit $?;
    pep8 || exit $?;
    python docs/coverage.py || exit $?;
  fi
- if [[ "$PYTHON_VM" == "pypy" ]]; then
    python -mlibearth.version;
    py.test --durations=20 tests || exit $?;
  fi
- if [[ "$PYTHON_VM" == "ironpython" ]]; then
    mono IronPython-2.7.4/ipy.exe -X:ExceptionDetail -X:ShowClrExceptions -X:FullFrames pytest.py -v -s --assert=plain tests || exit $?;
  fi
after_success:
- if [[ "$PYTHON_VM" == "cpython" ]]; then coveralls; fi
notifications:
  irc:
    channels:
    - "irc.ozinger.org#earthreader"
    on_success: change
    on_failure: always
